### ISSUE TITLE
recipent address in new message is incomplete

### ISSUE THREAD

**Issue by junkb** [barrydegraaff/list-unsubscribe-zimlet#3]
certain email address values in the List-Unsubscribe: header are parsed incorrectly into the compose message window:

List-Unsubscribe: <mailto:googlegroups-manage+1072985797931+unsubscribe@googlegroups.com>,
 <http://groups.google.com/group/puppet-users/subscribe>

![compose_message](https://cloud.githubusercontent.com/assets/7424193/10045522/58c7e878-61d1-11e5-8352-f5dfe479f515.png)

**Comment by barrydegraaff** [comment]
can you add the source of the email message to pastebin or somewere, so I can see the exact header.

Thanks

**Comment by junkb** [comment]
Return-Path: puppet-users+bncBDMMHIFY2IEBBQUWRGYAKGQE3LN5GWI@googlegroups.com
Received: from mfa.example.com (LHLO mfa.example.com) (10.3.70.9) by
 polaris.example.com with LMTP; Wed, 23 Sep 2015 02:48:54 -0400 (EDT)
X-Virus-Scanned: amavisd-new at example.com
X-Spam-Flag: NO
X-Spam-Score: -2.656
X-Spam-Level:
X-Spam-Status: No, score=-2.656 required=5 tests=[BAYES_00=-1.9,
	DKIM_SIGNED=0.1, DKIM_VALID=-0.1, DKIM_VALID_AU=-0.1,
	HEADER_FROM_DIFFERENT_DOMAINS=0.045, HTML_MESSAGE=0.001,
	RCVD_IN_DNSWL_LOW=-0.7, RCVD_IN_MSPIKE_H2=-0.001, SPF_PASS=-0.001]
	autolearn=no autolearn_force=no
X-Amavis-OS-Fingerprint: UNKNOWN [S30:45:0:60:M1430,S,T,N,W7:.:?:?] (up: 4453
	hrs), (link: (Google 2)), [209.85.213.64]:33912
Authentication-Results: mfa.example.com (amavisd-new); dkim=pass (2048-bit key)
	header.d=googlegroups.com header.b=RdoKWCPf; dkim=pass (1024-bit key)
	header.d=example.org header.b=G2HUlcEK
Received: from mta1.example.com ([10.3.70.5])
	by mfa.example.com (mfa.example.com [10.3.70.9]) (amavisd-new, port 11024)
	with LMTP id D8Pkg0_qvxah for <jdoe@example.com>;
	Wed, 23 Sep 2015 02:48:53 -0400 (EDT)
Received: from mail-vk0-f64.google.com (mail-vk0-f64.google.com [209.85.213.64])
	by mta1.example.com (Postfix) with ESMTPS id 3nLVTc6s1LzJmrC
	for <jdoe@example.com>; Wed, 23 Sep 2015 02:48:52 -0400 (EDT)
Received: by vkao3 with SMTP id o3sf5742291vka.1
        for <jdoe@example.com>; Tue, 22 Sep 2015 23:48:52 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=googlegroups.com; s=20120806;
        h=date:from:to:message-id:subject:mime-version:content-type
         :x-original-sender:reply-to:precedence:mailing-list:list-id
         :x-spam-checked-in-group:list-post:list-help:list-archive:sender
         :list-subscribe:list-unsubscribe;
        bh=HdAhEJfYJrFZHt8zQ7Wthkpzj+SglX6Ca5uiPclMScM=;
        b=RdoKWCPf8Kh6DQQca/xBMaCi7LBGDENnxzAiOThSi0dPNXxP4/SucPGT8o4i2Tuk7+
         d7UCXdQ7ns51FKMjNP7T4pGnbS4ZoTrjNFCZGCikJltUVHFTHPL00VL3gGecV8EK64TB
         AkhQHfGByKwgjiIyeSBRo3q4GYwBAJsCyCqVvULgBETW7UtzCkdEzcJN6aVprtFg/8Iy
         I+BwsYUX9MXXdkcdIzVrJJ7BG5mbpF8vjp4HOy/xMynwErq+etsyopbX6J83El9d/R/s
         d6ErjfbdU7kicOQy1909/+CBEvmuxoEKW/sYtFaLBZXzP+5Nbenibchv37rskkLeOLPl
         NFCA==
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=example.org; s=google;
        h=date:from:to:message-id:subject:mime-version:content-type
         :x-original-sender:reply-to:precedence:mailing-list:list-id
         :x-spam-checked-in-group:list-post:list-help:list-archive:sender
         :list-subscribe:list-unsubscribe;
        bh=HdAhEJfYJrFZHt8zQ7Wthkpzj+SglX6Ca5uiPclMScM=;
        b=G2HUlcEK7Zz2m6U78ZqzRm3Ys+mNBkyCL1cSztq3KbbUgieiszut6o8K0XR9j49uuy
         AvcrpzI4Q4E03QLxgE0z4Z9O/wiJem8fUvT1NFhBE8gulfHxJ3m1VOumgvct9rLiryKq
         5qg7ox6xB+UOrysv3q3teCP+uS2wJHCgbqDIw=
X-Received: by 10.140.19.85 with SMTP id 79mr212253qgg.22.1442990932079;
        Tue, 22 Sep 2015 23:48:52 -0700 (PDT)
X-BeenThere: puppet-users@googlegroups.com
Received: by 10.140.109.136 with SMTP id l8ls320653qgf.96.gmail; Tue, 22 Sep
 2015 23:48:33 -0700 (PDT)
X-Received: by 10.140.102.7 with SMTP id v7mr211839qge.19.1442990913832;
        Tue, 22 Sep 2015 23:48:33 -0700 (PDT)
Date: Tue, 22 Sep 2015 23:48:33 -0700 (PDT)
From: Sender <sender@example.org>
To: Puppet Users <puppet-users@googlegroups.com>
Message-Id: <7ef14a02-bf2a-465c-9410-2429e59b6f3c@googlegroups.com>
Subject: [Puppet Users] Can we lookup hiera data object providing the file name
MIME-Version: 1.0
Content-Type: multipart/mixed; 
	boundary="----=_Part_7916_1984785096.1442990913032"
X-Original-Sender: sender@example.org
Reply-To: puppet-users@googlegroups.com
Precedence: list
Mailing-list: list puppet-users@googlegroups.com; contact puppet-users+owners@googlegroups.com
List-ID: <puppet-users.googlegroups.com>
X-Spam-Checked-In-Group: puppet-users@googlegroups.com
X-Google-Group-Id: 1072985797931
List-Post: <http://groups.google.com/group/puppet-users/post>, <mailto:puppet-users@googlegroups.com>
List-Help: <http://groups.google.com/support/>, <mailto:puppet-users+help@googlegroups.com>
List-Archive: <http://groups.google.com/group/puppet-users
Sender: puppet-users@googlegroups.com
List-Subscribe: <http://groups.google.com/group/puppet-users/subscribe>, <mailto:puppet-users+subscribe@googlegroups.com>
List-Unsubscribe: <mailto:googlegroups-manage+1072985797931+unsubscribe@googlegroups.com>,
 <http://groups.google.com/group/puppet-users/subscribe>

------=_Part_7916_1984785096.1442990913032
Content-Type: multipart/alternative; 
	boundary="----=_Part_7917_281963502.1442990913033"

------=_Part_7917_281963502.1442990913033
Content-Type: text/plain; charset=UTF-8

I am using hiera lookup as follows in my puppet template

<%- nodeinfo = scope.function_hiera(['nodes']) -%>

I have provided the .yaml file which includes above 'nodes' object in my 
hiera.yaml file ( that is inside nodesfile.yaml file which is dynamically 
loaded as follows)

---
:backends:
  - yaml
:yaml:
  :datadir: /etc/puppet/hieradata
:hierarchy:
  - "%{::nodes_file}
  

I have want to load another data object into my puppet template but the 
problem is that data object is in a .yaml file which is not registered in 
my hiera.yaml file. I cannot register that file in my hiera.yaml. 

Is there anyway to load data object providing the file along with the 
lookup method. I do know the .yaml file name that object is in ?

-- 
You received this message because you are subscribed to the Google Groups "Puppet Users" group.
To unsubscribe from this group and stop receiving emails from it, send an email to puppet-users+unsubscribe@googlegroups.com.
To view this discussion on the web visit https://groups.google.com/d/msgid/puppet-users/7ef14a02-bf2a-465c-9410-2429e59b6f3c%40googlegroups.com.
For more options, visit https://groups.google.com/d/optout.

------=_Part_7917_281963502.1442990913033
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">I am using hiera lookup as follows in my puppet template<d=
iv><br></div><div><div><div class=3D"prettyprint" style=3D"border: 1px soli=
d rgb(187, 187, 187); word-wrap: break-word; background-color: rgb(250, 250=
, 250);"><code class=3D"prettyprint"><div class=3D"subprettyprint"><span st=
yle=3D"color: #660;" class=3D"styled-by-prettify">&lt;%-</span><span style=
=3D"color: #000;" class=3D"styled-by-prettify"> nodeinfo </span><span style=
=3D"color: #660;" class=3D"styled-by-prettify">=3D</span><span style=3D"col=
or: #000;" class=3D"styled-by-prettify"> scope</span><span style=3D"color: =
#660;" class=3D"styled-by-prettify">.</span><span style=3D"color: #000;" cl=
ass=3D"styled-by-prettify">function_hiera</span><span style=3D"color: #660;=
" class=3D"styled-by-prettify">([</span><span style=3D"color: #080;" class=
=3D"styled-by-prettify">&#39;nodes&#39;</span><span style=3D"color: #660;" =
class=3D"styled-by-prettify">])</span><span style=3D"color: #000;" class=3D=
"styled-by-prettify"> </span><span style=3D"color: #660;" class=3D"styled-b=
y-prettify">-</span><span style=3D"color: #000;" class=3D"styled-by-prettif=
y">%&gt;</span></div></code></div><br></div></div><div>I have provided the =
.yaml file which includes above &#39;nodes&#39; object in my hiera.yaml fil=
e ( that is inside nodesfile.yaml file which is dynamically loaded as follo=
ws)</div><div><br></div><div><div class=3D"prettyprint" style=3D"border: 1p=
x solid rgb(187, 187, 187); word-wrap: break-word; background-color: rgb(25=
0, 250, 250);"><code class=3D"prettyprint"><div class=3D"subprettyprint"><d=
iv class=3D"subprettyprint">---</div><div class=3D"subprettyprint">:backend=
s:</div><div class=3D"subprettyprint">=C2=A0 - yaml</div><div class=3D"subp=
rettyprint">:yaml:</div><div class=3D"subprettyprint">=C2=A0 :datadir: /etc=
/puppet/hieradata</div><div class=3D"subprettyprint">:hierarchy:</div><div =
class=3D"subprettyprint">=C2=A0 -=C2=A0&quot;%{::nodes_file}</div><div clas=
s=3D"subprettyprint">=C2=A0=C2=A0</div></div></code></div><br>I have want t=
o load another data object into my puppet template but the problem is that =
data object is in a .yaml file which is not registered in my hiera.yaml fil=
e. I cannot register that file in my hiera.yaml.=C2=A0</div><div><br></div>=
<div>Is there anyway to load data object providing the file along with the =
lookup method. I do know the .yaml file name that object is in ?</div></div=
>

<p></p>

-- <br />
You received this message because you are subscribed to the Google Groups &=
quot;Puppet Users&quot; group.<br />
To unsubscribe from this group and stop receiving emails from it, send an e=
mail to <a href=3D"mailto:puppet-users+unsubscribe@googlegroups.com">puppet=
-users+unsubscribe@googlegroups.com</a>.<br />
To view this discussion on the web visit <a href=3D"https://groups.google.c=
om/d/msgid/puppet-users/7ef14a02-bf2a-465c-9410-2429e59b6f3c%40googlegroups=
.com?utm_medium=3Demail&utm_source=3Dfooter">https://groups.google.com/d/ms=
gid/puppet-users/7ef14a02-bf2a-465c-9410-2429e59b6f3c%40googlegroups.com</a=
>.<br />
For more options, visit <a href=3D"https://groups.google.com/d/optout">http=
s://groups.google.com/d/optout</a>.<br />

------=_Part_7917_281963502.1442990913033--
------=_Part_7916_1984785096.1442990913032--
